#!/bin/bash

### Colored Environment Variables
RED="$(tput setaf 1)$(tput bold)"
GREEN="$(tput setaf 2)$(tput bold)"
YELLOW="$(tput setaf 3)$(tput bold)"
NOATTR="$(tput sgr0)"

### Configure Archlinux System
if [ "$(uname -m)" = "x86_64" ]; then
	sed -i 's/#Server = http/Server = http/' /etc/pacman.d/mirrorlist
fi

### Initialize pacman key
pacman-key --init
if [ "$(uname -m)" = "x86_64" ]; then
	pacman-key --populate archlinux
else
	pacman-key --populate archlinuxarm
fi

### Change Default Locale
echo "en_US.UTF-8 UTF-8" > /etc/locale.gen

### Install some relevant packages
echo "${GREEN}Removing Linux Kernel if possible${NOATTR}"
## Remove Kernel which is not necessary
case "$(uname -m)" in
		aarch64)
			pacman -Rnsc --noconfirm linux-aarch64
			;;
		armv7l|armv8l)
			pacman -Rnsc --noconfirm linux-armv7
			;;
esac
echo "${GREEN}Updating the system and installing some packages${NOATTR}"
pacman -Syu --noconfirm
pacman -S sudo nano --noconfirm

echo "${GREEN}Adding the user ${YELLOW}user${NOATTR}"
useradd -m user -s /bin/bash
echo "user ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/user
