#!/bin/bash

## Add 'contrib non-free' componenets
sed -i 's/main/main contrib non-free/g' /etc/apt/sources.list ||:

## Delete Docker Files
rm -rf /etc/apt/apt.conf.d/docker-* ||:

### Colored Environment Variables
RED="$(tput setaf 1)$(tput bold)"
GREEN="$(tput setaf 2)$(tput bold)"
YELLOW="$(tput setaf 3)$(tput bold)"
NOATTR="$(tput sgr0)"

### Install some relevant packages
echo "${GREEN}Updating the system and installing some packages${NOATTR}"
apt update
apt install sudo nano -y ||:
apt install -f ||:
dpkg --configure -a

echo "${GREEN}Adding the user ${YELLOW}user${NOATTR}"
useradd -m user -s /bin/bash
echo "user ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/user