#!/bin/bash

### Change archive to old.releases
sed -i 's/archive.ubuntu/old-releases.ubuntu/g' /etc/apt/sources.list ||:
sed -i 's|ports.ubuntu.com/ubuntu-ports|old-releases.ubuntu.com/ubuntu|g' /etc/apt/sources.list ||:

### Colored Environment Variables
RED="$(tput setaf 1)$(tput bold)"
GREEN="$(tput setaf 2)$(tput bold)"
YELLOW="$(tput setaf 3)$(tput bold)"
NOATTR="$(tput sgr0)"

### Install some relevant packages
echo "${GREEN}Updating the system and installing some packages${NOATTR}"
apt update
apt install sudo nano -y ||:
apt install -f ||:
dpkg --configure -a

echo "${GREEN}Adding the user ${YELLOW}user${NOATTR}"
useradd -m user -s /bin/bash
echo "user ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/user