#!/bin/bash

## Set [trusted=yes] by default in order to continue using apt
sed -i 's/deb htt/deb [trusted=yes] htt/g' /etc/apt/sources.list ||:

### Colored Environment Variables
RED="$(tput setaf 1)$(tput bold)"
GREEN="$(tput setaf 2)$(tput bold)"
YELLOW="$(tput setaf 3)$(tput bold)"
NOATTR="$(tput sgr0)"

### Install some relevant packages
echo "${GREEN}Updating the system and installing some packages${NOATTR}"
apt update
apt install sudo nano -y ||:
apt install -f ||:
dpkg --configure -a

### Do not load tun devices at login
echo > /root/.bash_profile

echo "${GREEN}Adding the user ${YELLOW}user${NOATTR}"
useradd -m user -s /bin/bash
echo "user ALL=(ALL:ALL) NOPASSWD:ALL" > /etc/sudoers.d/user