#!/data/data/com.termux/files/usr/bin/bash
### rlc-create - create chroots from tarballs and installs them with templates
### All Rights Reserved @wmcbtech30 (2021)
###
### Supported Distributions:
### * Ubuntu (Oldstable LTS/Stable LTS)
### * Debian (Buster/Stretch/Sid/Testing)
### * Kali (Rolling)
### * Alpine (Stable/Edge)
###
### Templates are registered in:
### $PREFIX/var/rlc/distro-templates
RLCHROOT_ROOTFS_DIR="$PREFIX/var/rlc/containers"
RLCHROOT_TEMPLATES="$PREFIX/var/rlc/distro-templates"
RLCHROOT_CACHE="$PREFIX/var/rlc/cache"
DISTRO_NAME="$1"
CHROOT_NAME="$2"

### Colored Environment Variables
RED="$(tput setaf 1)$(tput bold)"
GREEN="$(tput setaf 2)$(tput bold)"
YELLOW="$(tput setaf 3)$(tput bold)"
NOATTR="$(tput sgr0)"

### SIGNAL Trap
sigtrap(){
echo "${RED}Signal Recieved! Exiting as Requested...${NOATTR}"
exit 2
}

trap 'sigtrap' HUP INT KILL QUIT TERM

### Check if running as root
if [ "$(whoami)" == "root" ]; then
	echo "${RED}Running ${YELLOW}rlc-create${RED} as root is discouraged, Aborting Exit Code 2${NOATTR}"
	exit 2
fi

### Check Architecture Function
check_arch(){
case "$(uname -m)" in
	arm|armhf|armv7*|arm32)
		DIST_ARCH_DEBIAN="dist-arm32v7"
		DIST_ARCH_UBUNTU="armhf"
		DIST_ARCH_ALPINE="armhf"
		;;
	arm64|aarch64|armv8*)
		DIST_ARCH_DEBIAN="dist-arm64v8"
		DIST_ARCH_UBUNTU="arm64"
		DIST_ARCH_ALPINE="aarch64"
		;;
	amd64|x86_64)
		DIST_ARCH_DEBIAN="dist-amd64"
		DIST_ARCH_UBUNTU="amd64"
		DIST_ARCH_ALPINE="x86_64"
		;;
	i686|i586|i386|x86|x86_32)
		DIST_ARCH_DEBIAN="dist-i386"
		DIST_ARCH_UBUNTU="i386"
		DIST_ARCH_ALPINE="x86"
		;;
esac
}

### Check if no argument is specified
if [ $# = 0 ] || [ $1 == "--help" ]; then
	echo "${GREEN}rlc-create: Install Chroots from Tarballs"
	echo ""
	echo "Usage: "
	echo "rlc-create ${YELLOW}[DISTRO-FLAVOR] [CHROOT-NAME]"
	echo ""
	echo "${GREEN}Supported Distributions: "
	echo "${YELLOW} Ubuntu"
	echo " Debian"
	echo " Kali"
	echo " Alpine"
	echo "${GREEN}You can view the list of available flavors with ${YELLOW}rlc-create list${GREEN} command"
	echo ""
	echo "Example Usage: "
	echo "${YELLOW}rlc-create stretch stretchfs"
	echo "rlc-create kali kali-rootfs"
	echo ""
	echo "${GREEN}If you want to delete the container, run ${YELLOW}rlc-destroy${GREEN} command${NOATTR}"
	exit 2
fi

list_distros(){
	echo "${GREEN}Supported Distributions:"
	echo ""
	echo "Debian:"
	echo "${YELLOW}stretch, buster, bullseye, testing, sid"
	echo ""
	echo "${GREEN}Ubuntu:"
	echo "${YELLOW}bionic, cosmic, disco, eoan, focal, groovy"
	echo ""
	echo "${GREEN}Kali:"
	echo "${YELLOW}kali (rolling)${NOATTR}"
	echo ""
	echo "${GREEN}Alpine:"
	echo "alpine-stable alpine-edge"
}

### Distro-Specific Functions
bionic(){
	EXPECT="ubuntu-bionic-$(uname -m).tar.gz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/bionic/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://partner-images.canonical.com/core/bionic/current/ubuntu-bionic-core-cloudimg-${DIST_ARCH_UBUNTU}-root.tar.gz"
	TEMPLATE="$RLCHROOT_TEMPLATES/bionic"
}

focal(){
	EXPECT="ubuntu-focal-$(uname -m).tar.gz"
	STRIP_TARBALL=0
	### Ubuntu 20.04 Drops support for 32-bit anymore
	if [ "$(uname -m)" == "i686" ]; then
		echo "${RED}WARNING: Ubuntu 20.04 Drops support for 32-bit anymore${NOATTR}"
		exit 2
	fi
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/focal/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://partner-images.canonical.com/core/focal/current/ubuntu-focal-core-cloudimg-${DIST_ARCH_UBUNTU}-root.tar.gz"
	TEMPLATE="$RLCHROOT_TEMPLATES/focal"
}

eoan(){
	EXPECT="ubuntu-eoan-$(uname -m).tar.gz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/eoan/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://partner-images.canonical.com/core/eoan/current/ubuntu-eoan-core-cloudimg-${DIST_ARCH_UBUNTU}-root.tar.gz"
	TEMPLATE="$RLCHROOT_TEMPLATES/eoan"
}

disco(){
	EXPECT="ubuntu-disco-$(uname -m).tar.gz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/disco/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://partner-images.canonical.com/core/unsupported/disco/current/ubuntu-disco-core-cloudimg-${DIST_ARCH_UBUNTU}-root.tar.gz"
	TEMPLATE="$RLCHROOT_TEMPLATES/disco"
}

cosmic(){
	EXPECT="ubuntu-cosmic-$(uname -m).tar.gz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/cosmic/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://partner-images.canonical.com/core/unsupported/cosmic/current/ubuntu-cosmic-core-cloudimg-${DIST_ARCH_UBUNTU}-root.tar.gz"
	TEMPLATE="$RLCHROOT_TEMPLATES/cosmic"
}

groovy(){
	EXPECT="ubuntu-groovy-$(uname -m).tar.gz"
	STRIP_TARBALL=0
	### Ubuntu 20.10 Drops support for 32-bit anymore
	if [ "$(uname -m)" == "i686" ]; then
		echo "${RED}WARNING: Ubuntu 20.10 Drops support for 32-bit anymore${NOATTR}"
		exit 2
	fi
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/groovy/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://partner-images.canonical.com/core/groovy/current/ubuntu-groovy-core-cloudimg-${DIST_ARCH_UBUNTU}-root.tar.gz"
	TEMPLATE="$RLCHROOT_TEMPLATES/groovy"
}

buster(){
	EXPECT="debian-buster-$(uname -m).tar.xz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/buster/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://github.com/debuerreotype/docker-debian-artifacts/raw/${DIST_ARCH_DEBIAN}/buster/rootfs.tar.xz"
	TEMPLATE="$RLCHROOT_TEMPLATES/buster"
}

stretch(){
	EXPECT="debian-stretch-$(uname -m).tar.xz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/stretch/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://github.com/debuerreotype/docker-debian-artifacts/raw/${DIST_ARCH_DEBIAN}/stretch/rootfs.tar.xz"
	TEMPLATE="$RLCHROOT_TEMPLATES/stretch"
}

bullseye(){
	EXPECT="debian-bullseye-$(uname -m).tar.xz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/bullseye/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://github.com/debuerreotype/docker-debian-artifacts/raw/${DIST_ARCH_DEBIAN}/bullseye/rootfs.tar.xz"
	TEMPLATE="$RLCHROOT_TEMPLATES/bullseye"
}

sid(){
	EXPECT="debian-sid-$(uname -m).tar.xz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/sid/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://github.com/debuerreotype/docker-debian-artifacts/raw/${DIST_ARCH_DEBIAN}/sid/rootfs.tar.xz"
	TEMPLATE="$RLCHROOT_TEMPLATES/sid"
}

testing(){
	EXPECT="debian-testing-$(uname -m).tar.xz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/testing/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://github.com/debuerreotype/docker-debian-artifacts/raw/${DIST_ARCH_DEBIAN}/testing/rootfs.tar.xz"
	TEMPLATE="$RLCHROOT_TEMPLATES/testing"
}

kali(){
	EXPECT="kali-$(uname -m).tar.xz"
	STRIP_TARBALL=1
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/kali/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://build.nethunter.com/kalifs/kalifs-latest/kalifs-${DIST_ARCH_UBUNTU}-minimal.tar.xz"
	TEMPLATE="$RLCHROOT_TEMPLATES/kali"
}

alpine-stable(){
	EXPECT="alpine-stable-$(uname -m).tar.gz"
	STRIP_TARBALL=0
	### Declare Configs
	check_arch
	if [ -e "$RLCHROOT_CACHE/alpine-stable/$EXPECT" ]; then
		DO_NOT_WGET=1
	fi
	WGET_URL_LINK="https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/${DIST_ARCH_ALPINE}/alpine-minirootfs-3.12.3-${DIST_ARCH_ALPINE}.tar.gz"

	TEMPLATE="$RLCHROOT_TEMPLATES/alpine-stable"
}

alpine-edge(){
    EXPECT="alpine-edge-$(uname -m).tar.gz"
    STRIP_TARBALL=0
    ### Declare Configs
    check_arch
    if [ -e "$RLCHROOT_CACHE/alpine-edge/$EXPECT" ]; then
        DO_NOT_WGET=1
    fi
    WGET_URL_LINK="https://dl-cdn.alpinelinux.org/alpine/edge/releases/${DIST_ARCH_ALPINE}/alpine-minirootfs-3.12.0-${DIST_ARCH_ALPINE}.tar.gz"

    TEMPLATE="$RLCHROOT_TEMPLATES/alpine-edge"
}

### Explicitly Check for Zero String for Argument
if [ -z "$DISTRO_NAME" ]; then
	echo "${RED}Please Specify a Distribution Name you want to install!${NOATTR}"
	exit 2
fi

case "$DISTRO_NAME" in
	bionic|ubuntu-bionic)
		DIST=bionic
		bionic
		;;
	focal|ubuntu-focal)
		DIST=focal
		focal
		;;
	eoan|ubuntu-eoan)
		DIST=eoan
		eoan
		;;
	disco|ubuntu-disco)
		DIST=disco
		disco
		;;
	cosmic|ubuntu-cosmic)
		DIST=cosmic
		cosmic
		;;
	groovy|ubuntu-groovy)
		DIST=groovy
		groovy
		;;
	buster|debian-buster)
		DIST=buster
		buster
		;;
	stretch|debian-stretch)
		DIST=stretch
		stretch
		;;
	bullseye|debian-bullseye)
		DIST=bullseye
		bullseye
		;;
	sid|unstable|debian-unstable|debian-sid)
		DIST=sid
		sid
		;;
	testing|debian-testing)
		DIST=testing
		testing
		;;
	kali|kali-rolling)
		DIST=kali
		kali
		;;
	alpine-stable)
		DIST=alpine-stable
		alpine-stable
		;;
	alpine-edge)
		DIST=alpine-edge
		alpine-edge
		;;
	list)
		list_distros
		exit 0
		;;
	*)
		echo "${RED}Unknown Distribution was requested: $DISTRO_NAME ${NOATTR}"
		exit 2
		;;
esac

### Explicitly Check for Zero String for Argument
if [ -z "$CHROOT_NAME" ]; then
	echo "${RED}Please Specify a Container Name${NOATTR}"
	exit 2
fi

### Check if the container is installed
if [ -e "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME" ]; then
	echo "${RED}The Container ${YELLOW}$CHROOT_NAME${RED} is already installed${NOATTR}"
	exit 2
fi

get_fs_image(){
	echo "${GREEN}Downloading the Image File: ${YELLOW}$DISTRO_NAME${NOATTR} "
	echo
	mkdir -p "$RLCHROOT_CACHE/$DIST" ||:
	wget --tries=5 "$WGET_URL_LINK" -O "$RLCHROOT_CACHE/$DIST/$EXPECT.part"
		if [ -e "$RLCHROOT_CACHE/$DIST/$EXPECT.part" ]; then
			mv "$RLCHROOT_CACHE/$DIST/$EXPECT.part" "$RLCHROOT_CACHE/$DIST/$EXPECT"
			DESTPATH="$RLCHROOT_CACHE/$DIST/$EXPECT"
		else
			echo "${RED}An Error has occured: no such file or directory${NOATTR}"
			exit 2
		fi
}

do_extract_filesystem(){
	DESTPATH="$RLCHROOT_CACHE/$DIST/$EXPECT"
	echo
	echo "${GREEN}Installing the rootfs ${YELLOW}$DISTRO_NAME${GREEN}. This may take some time${NOATTR}"
	mkdir "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME" -p ||:
	proot --link2symlink -0 tar --preserve-permissions --delay-directory-restore --strip="$STRIP_TARBALL" -xf "$DESTPATH" --exclude dev -C "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME" ||:
}

setup_android_groups(){
	echo "aid_$(id -un):x:$(id -u):$(id -g):Android UID:/:/usr/sbin/nologin" >> "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/etc/passwd"
	echo "aid_$(id -un):*:18446:0:99999:7:::" >> "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/etc/shadow"
		for g in $(id -G); do
			echo "aid_$(id -gn "$g"):x:${g}:root,aid_$(id -un)" >> "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/etc/group"
			if [ -f "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/etc/gshadow" ]; then
				echo "aid_$(id -gn "$g"):*::root,aid_$(id -un)" >> "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/etc/gshadow"
			fi
		done
}

setup_nameserver(){
	cat > "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/etc/resolv.conf" <<- EOM
	nameserver 8.8.8.8
	nameserver 8.8.4.4
	EOM
}

if [ "$DO_NOT_WGET" == "1" ]; then
	do_extract_filesystem
else
	get_fs_image
	do_extract_filesystem
fi

TEMPLATE_CFG="$RLCHROOT_TEMPLATES/$DIST"
### Function to run proot command for template configuration
proot_run_cmd(){
	echo "${GREEN}Performing Distro-Specific Steps${NOATTR}"
	setup_android_groups
	setup_nameserver
	unset LD_PRELOAD
	proot --link2symlink --root-id --kernel-release=4.14.144-lxc --rootfs="$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME" --bind=/dev --bind=/proc --bind=/sys \
	--cwd=/root \
	/usr/bin/env -i \
	HOME=/root \
	PATH=/usr/local/bin:/usr/local/sbin:/usr/local/games:/usr/bin:/usr/sbin:/usr/games:/bin:/sbin:/opt \
	USER=root \
	LANG=C.UTF-8 \
	TERM=$TERM \
	/opt/template-config.sh
}

### Copy Template Path
install -m 755 "$TEMPLATE_CFG" "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/opt/template-config.sh"

### Setup the Distribution and indicate the success
if proot_run_cmd; then
	rm -rf "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/opt/template-config.sh" ||:
	echo 
	echo "${GREEN}The container ${YELLOW}$CHROOT_NAME${GREEN} successfully installed${NOATTR}"
	exit 0
else
	rm -rf "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME/opt/template-config.sh" ||:
	echo 
	echo "${RED}An Error has occured during the distro setup, please reinstall it if possible${NOATTR}"
	exit 2
fi

### END OF MESSAGE EOM
