#!/data/data/com.termux/files/usr/bin/bash
### rlc-export - exports the containers into tarball used for publishing images
### All Rights Reserved @wmcbtech30 (2021)
RLCHROOT_ROOTFS_DIR="$PREFIX/var/rlc/containers"
BACKUP_DIR="$HOME/exported_containers"
TIMESTAMP="$(date +%s)"
CHROOT_NAME="$1"


### Colored Environment Variables
RED="$(tput setaf 1)$(tput bold)"
GREEN="$(tput setaf 2)$(tput bold)"
YELLOW="$(tput setaf 3)$(tput bold)"
NOATTR="$(tput sgr0)"

sigtrap(){
echo "${RED}Signal Recieved! Exiting as Requested...${NOATTR}"
exit 2
}

trap 'sigtrap' HUP INT KILL QUIT TERM

### Check if running as root
if [ "$(whoami)" == "root" ]; then
	echo "${RED}Running ${YELLOW}rlc-export${RED} as root is discouraged, Aborting Exit Code 2${NOATTR}"
	exit 2
fi

### Check if no argument is specified
if [ $# = 0 ] || [ $1 == "--help" ]; then
	echo "${GREEN}rlc-export: Exports Containers into gzip tarball"
	echo ""
	echo "Usage: "
	echo "${YELLOW}rlc-export [CHROOT-NAME]"
	echo ""
	echo "${GREEN}Example Usage: "
	echo "${YELLOW}rlc-export kali-rootfs"
	echo "rlc-export ubuntu-focal"
	echo ""
	echo "${GREEN}NOTE: To avoid data corruption, close all containers before exporting"
	echo "By Default, exported containers will be placed in \$HOME/exported_containers ${NOATTR}"
	exit 2
fi

### Explicitly Check for Zero String for Argument
if [ -z "$CHROOT_NAME" ]; then
	echo "${RED}Please Specify a Container Name to Export${NOATTR}"
	exit 2
fi

### Check if the Container Exists
if [ ! -e "$RLCHROOT_ROOTFS_DIR/$CHROOT_NAME" ]; then
	echo "${RED}The Requested Container ${YELLOW}$CHROOT_NAME${RED} isn't installed${NOATTR}"
	exit 2
fi

### Setup Backup Directory
mkdir -p "$BACKUP_DIR"

### Go To the Container dir to avoid adding subdirectory
cd "$RLCHROOT_ROOTFS_DIR"

### Backup the Container
echo "${YELLOW}Backing Up $RLCHROOT_ROOTFS_DIR/$CHROOT_NAME...${NOATTR}"
if tar --preserve-permissions -zcf "$BACKUP_DIR/$CHROOT_NAME-$TIMESTAMP.tar.gz" "$CHROOT_NAME"; then
	success=yes
else
	success=no
fi

if [ "$success" == "yes" ]; then
    echo "${GREEN}The Container Successfully Exported"
	echo "Your file is placed in:"
	echo "${YELLOW}$BACKUP_DIR/$CHROOT_NAME-$TIMESTAMP.tar.gz${NOATTR}"
    exit 0
else
    echo "${RED}The Container Successfully Exported with Errors${NOATTR}"
    exit 2
fi

### END OF MESSAGE EOM

