#!/data/data/com.termux/files/usr/bin/bash
### rlc-import - imports the container for restoring
### All Rights Reserved @wmcbtech30 (2021)
RLCHROOT_ROOTFS_DIR="$PREFIX/var/rlc/containers"
INPUT_ARG="$1"

### Colored Environment Variables
RED="$(tput setaf 1)$(tput bold)"
GREEN="$(tput setaf 2)$(tput bold)"
YELLOW="$(tput setaf 3)$(tput bold)"
NOATTR="$(tput sgr0)"

sigtrap(){
echo "${RED}Signal Recieved! Exiting as Requested...${NOATTR}"
exit 2
}

trap 'sigtrap' HUP INT KILL QUIT TERM

### Check if running as root
if [ "$(whoami)" == "root" ]; then
	echo "${RED}Running ${YELLOW}rlc-import${RED} as root is discouraged, Aborting Exit Code 2${NOATTR}"
	exit 2
fi

### Check if no argument is specified
if [ $# = 0 ] || [ $1 == "--help" ]; then
	echo "${GREEN}rlc-import: Imports Containers from Tarball"
	echo ""
	echo "Usage: "
	echo "${YELLOW}rlc-import [TARBALL]"
	echo ""
	echo "${GREEN}Example Usage: "
	echo "${YELLOW}rlc-import ubuntu-backup-arm64.tar.gz"
	echo "rlc-import kali-backup.dump"
	echo ""
	echo "${GREEN}NOTE: Using this tool will not perform any sanity checks"
	echo "So Be careful on what you're trying to import as data loss will occur${NOATTR}"
	exit 2
fi

### Explicitly Check for Zero String for Argument
if [ -z "$INPUT_ARG" ]; then
	echo "${RED}Please Specify a Tarball to Import${NOATTR}"
	exit 2
fi

### Check if the file exists
if [ ! -e "$INPUT_ARG" ]; then
	echo "${RED}Cannot Import the Container: no such file or directory${NOATTR}"
	exit 2
fi


read -p "${GREEN}Do you want to import ${YELLOW}$INPUT_ARG${GREEN}? [y/N] ${GREEN}" yn
case $yn in
	Y*|y*) ;;
	N*|n*) echo "${YELLOW}Aborting...${NOATTR}"; exit 0;;
	*) echo "${YELLOW}Aborting...${NOATTR}"; exit 0;;
esac

### Restore the container
echo "${YELLOW}Importing Container from file $INPUT_ARG...${NOATTR}"
if tar --recursive-unlink --delay-directory-restore --preserve-permissions -zxf "$INPUT_ARG" -C "$RLCHROOT_ROOTFS_DIR" >/dev/null 2>&1; then
	success=yes
else
	success=no
fi

if [ "$success" == "yes" ]; then
	echo "${GREEN}The Container Successfully Imported${NOATTR}"
	exit 0
else
	echo "${RED}The Container Successfully Imported with Errors${NOATTR}"
	exit 2
fi

### END OF MESSAGE EOM
