# This is a basic workflow to help you get started with Actions

name: Shell Checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@v0.1.8
